CRITICAL - 2025-02-03 21:23:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: test]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 231.
 1 APPPATH\Controllers\Home.php(16): CodeIgniter\Database\MySQLi\Connection->connect()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->pruebaconexion()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-02-03 21:23:21 --> [Caused by] mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 186.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
 2 APPPATH\Controllers\Home.php(16): CodeIgniter\Database\MySQLi\Connection->connect()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->pruebaconexion()
 4 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
